model:
  - seqNTL
trainer:
  - NTL
network:
  - seqNTL
device:
  - cuda
x_length:
  - 100
learning_rate:
  - 0.001
training_epochs:
  - 50
train_method:
  - loe_soft
latent_dim:
  - 64
enc_hdim:
  - 32
enc_nlayers:
  - 3
num_trans:
  - 10
trans_nlayers:
  - 3
trans_type:
  - residual
loss:
  - DCL
enc_bias:
  - False
batch_norm:
  - False
loss_temp:
  - 0.1
l2:
  - 0.00001
optimizer:
  - Adam
scheduler:
  -
    class: StepLR
    args:
      step_size: 100
      gamma: 0.5
early_stopper:
  -
    class: Patience
    args:
      patience: 100
      use_train_loss: True

shuffle:
  - True
num_repeat:
  - 1
save_scores:
  - False
result_folder:
  - RESULTS/time_series_simulation/
